alter session set "_ORACLE_SCRIPT"=true;

DROP USER BO CASCADE;
CREATE USER BO IDENTIFIED BY BO;
GRANT CONNECT, RESOURCE, DBA TO BO;

DROP USER TP12062763 CASCADE;
CREATE USER TP12062763 IDENTIFIED BY garneau;
GRANT CONNECT, RESOURCE, DBA TO TP12062763;
COMMIT;